import type { Vehicle } from '@/types';

export const VEHICLE_PHOTOS = [
  '/images/vehicles/pictures/photo_1_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_2_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_3_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_4_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_5_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_6_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_7_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_8_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_9_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_10_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_11_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_12_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_13_2026-02-26_22-04-45.jpg',
  '/images/vehicles/pictures/photo_1_2026-02-26_22-06-54.jpg',
  '/images/vehicles/pictures/photo_2_2026-02-26_22-06-54.jpg',
];

export const VEHICLE_DESCRIPTIONS = [
  'Надёжная техника для покорения любого бездорожья. Мощный двигатель и усиленная подвеска обеспечивают уверенную езду в самых сложных условиях.',
  'Создан для настоящих приключений. Современная система полного привода и электронное управление делают каждую поездку незабываемой.',
  'Премиальная модель с максимальной комплектацией. Спортивный характер сочетается с комфортом для дальних путешествий.',
  'Универсальная модель для работы и отдыха. Высокая грузоподъёмность и экономичный расход топлива — идеальный баланс.',
  'Флагман линейки с непревзойдённой динамикой. Турбированный двигатель и адаптивная подвеска для экстремальных нагрузок.',
  'Компактная и манёвренная модель для новичков и профессионалов. Лёгкое управление и отличная проходимость.',
  'Топовая комплектация для требовательных райдеров. Усиленная рама, защита днища и мощная лебёдка в стандарте.',
  'Спортивная модель для скоростных трасс и бездорожья. Агрессивный дизайн и впечатляющая мощность.',
  'Туристическая модель повышенной комфортности. Мягкая подвеска, подогрев ручек и вместительный багажник.',
  'Профессиональная техника для экспедиций и долгих маршрутов. Увеличенный запас хода и надёжная конструкция.',
  'Модель для экстремального катания в горах. Лёгкая платформа и мощный двигатель для глубокого снега.',
  'Стильный и современный дизайн в сочетании с передовыми технологиями. Лучший выбор сезона.',
];

export function getRandomImage(): string {
  return VEHICLE_PHOTOS[Math.floor(Math.random() * VEHICLE_PHOTOS.length)];
}

export function getRandomDescription(): string {
  return VEHICLE_DESCRIPTIONS[Math.floor(Math.random() * VEHICLE_DESCRIPTIONS.length)];
}

export const vehicles: Vehicle[] = [
  {
    id: '1',
    slug: 'can-am-outlander-700',
    name: 'Can-Am Outlander 700',
    type: 'atv',
    brand: 'brp',
    year: 2024,
    price: 1350000,
    rentalPrice: 8000,
    images: [VEHICLE_PHOTOS[0]],
    description: 'Мощный квадроцикл для бездорожья с двигателем Rotax 650 куб.см. Идеален для охоты, рыбалки и активного отдыха.',
    specs: {
      engine: 'Rotax 650 куб.см, V-Twin',
      power: '48 л.с.',
      weight: '324 кг',
      maxSpeed: '105 км/ч',
      fuelCapacity: '20.5 л',
    },
    isAvailable: true,
    isRentable: true,
    isFeatured: true,
  },
  {
    id: '2',
    slug: 'polaris-sportsman-570',
    name: 'Polaris Sportsman 570',
    type: 'atv',
    brand: 'polaris',
    year: 2024,
    price: 980000,
    rentalPrice: 6000,
    images: ['/images/vehicles/sportsman-570.webp'],
    description: 'Универсальный квадроцикл Polaris с проверенным двигателем ProStar. Отличная управляемость и надёжность.',
    specs: {
      engine: 'ProStar 567 куб.см',
      power: '44 л.с.',
      weight: '291 кг',
      maxSpeed: '97 км/ч',
      fuelCapacity: '17.1 л',
    },
    isAvailable: true,
    isRentable: true,
    isFeatured: true,
  },
  {
    id: '3',
    slug: 'can-am-maverick-x3',
    name: 'Can-Am Maverick X3 X RS',
    type: 'buggy',
    brand: 'brp',
    year: 2024,
    price: 3200000,
    rentalPrice: 15000,
    images: ['/images/vehicles/maverick-x3.webp'],
    description: 'Флагманский багги Can-Am с турбированным двигателем Rotax 900 ACE. Непревзойдённая мощность и управляемость.',
    specs: {
      engine: 'Rotax 900 ACE Turbo RR',
      power: '200 л.с.',
      weight: '680 кг',
      maxSpeed: '140 км/ч',
      fuelCapacity: '40 л',
    },
    isAvailable: true,
    isRentable: true,
    isFeatured: true,
  },
  {
    id: '4',
    slug: 'polaris-rzr-pro-xp',
    name: 'Polaris RZR Pro XP',
    type: 'buggy',
    brand: 'polaris',
    year: 2024,
    price: 2800000,
    rentalPrice: 12000,
    images: ['/images/vehicles/rzr-pro-xp.webp'],
    description: 'Высокопроизводительный UTV Polaris с турбодвигателем. Создан для экстремального бездорожья.',
    specs: {
      engine: 'ProStar 925 куб.см Turbo',
      power: '181 л.с.',
      weight: '695 кг',
      maxSpeed: '135 км/ч',
      fuelCapacity: '36 л',
    },
    isAvailable: true,
    isRentable: false,
    isFeatured: true,
  },
  {
    id: '5',
    slug: 'ski-doo-summit-x-850',
    name: 'Ski-Doo Summit X 850 E-TEC',
    type: 'snowmobile',
    brand: 'brp',
    year: 2024,
    price: 1750000,
    rentalPrice: 10000,
    images: ['/images/vehicles/summit-x-850.webp'],
    description: 'Горный снегоход Ski-Doo для глубокого снега. Лёгкая платформа REV Gen4 и мощный двигатель E-TEC.',
    specs: {
      engine: 'Rotax 850 E-TEC, 2-тактный',
      power: '165 л.с.',
      weight: '215 кг',
      maxSpeed: '160 км/ч',
      fuelCapacity: '36 л',
    },
    isAvailable: true,
    isRentable: true,
    isFeatured: true,
  },
  {
    id: '6',
    slug: 'polaris-800-pro-rmk',
    name: 'Polaris 850 PRO-RMK',
    type: 'snowmobile',
    brand: 'polaris',
    year: 2024,
    price: 1600000,
    rentalPrice: 9000,
    images: ['/images/vehicles/pro-rmk-850.webp'],
    description: 'Горный снегоход Polaris с шасси AXYS и мощным двигателем Patriot 850. Лучший выбор для горных маршрутов.',
    specs: {
      engine: 'Patriot 850, 2-тактный',
      power: '160 л.с.',
      weight: '208 кг',
      maxSpeed: '155 км/ч',
      fuelCapacity: '42 л',
    },
    isAvailable: true,
    isRentable: true,
    isFeatured: false,
  },
  {
    id: '7',
    slug: 'sea-doo-rxp-x-300',
    name: 'Sea-Doo RXP-X 300',
    type: 'jetski',
    brand: 'brp',
    year: 2024,
    price: 2100000,
    rentalPrice: 12000,
    images: ['/images/vehicles/rxp-x-300.webp'],
    description: 'Спортивный водный мотоцикл Sea-Doo с суперчарджером. Максимальная скорость и манёвренность на воде.',
    specs: {
      engine: 'Rotax 1630 ACE с компрессором',
      power: '300 л.с.',
      weight: '186 кг',
      maxSpeed: '120 км/ч',
      fuelCapacity: '70 л',
    },
    isAvailable: true,
    isRentable: true,
    isFeatured: true,
  },
  {
    id: '8',
    slug: 'sea-doo-spark-trixx',
    name: 'Sea-Doo Spark Trixx',
    type: 'jetski',
    brand: 'brp',
    year: 2024,
    price: 750000,
    rentalPrice: 5000,
    images: ['/images/vehicles/spark-trixx.webp'],
    description: 'Компактный и манёвренный гидроцикл для трюков и весёлого катания. Лёгкий и экономичный.',
    specs: {
      engine: 'Rotax 900 ACE',
      power: '90 л.с.',
      weight: '186 кг',
      maxSpeed: '80 км/ч',
      fuelCapacity: '30 л',
    },
    isAvailable: true,
    isRentable: true,
    isFeatured: false,
  },
  {
    id: '9',
    slug: 'can-am-outlander-1000r',
    name: 'Can-Am Outlander 1000R XT-P',
    type: 'atv',
    brand: 'brp',
    year: 2024,
    price: 1950000,
    rentalPrice: 11000,
    images: ['/images/vehicles/outlander-1000r.webp'],
    description: 'Флагманский квадроцикл Can-Am с двигателем V-Twin 976 куб.см. Максимальная мощность для серьёзного бездорожья.',
    specs: {
      engine: 'Rotax 976 куб.см, V-Twin',
      power: '91 л.с.',
      weight: '368 кг',
      maxSpeed: '120 км/ч',
      fuelCapacity: '20.5 л',
    },
    isAvailable: true,
    isRentable: true,
    isFeatured: false,
  },
  {
    id: '10',
    slug: 'polaris-ranger-xp-1000',
    name: 'Polaris Ranger XP 1000',
    type: 'buggy',
    brand: 'polaris',
    year: 2024,
    price: 2200000,
    rentalPrice: 10000,
    images: ['/images/vehicles/ranger-xp-1000.webp'],
    description: 'Утилитарный UTV Polaris с грузовой платформой. Идеален для работы и отдыха.',
    specs: {
      engine: 'ProStar 999 куб.см',
      power: '82 л.с.',
      weight: '726 кг',
      maxSpeed: '100 км/ч',
      fuelCapacity: '42 л',
    },
    isAvailable: true,
    isRentable: false,
    isFeatured: false,
  },
  {
    id: '11',
    slug: 'ski-doo-renegade-900',
    name: 'Ski-Doo Renegade Adrenaline 900 ACE',
    type: 'snowmobile',
    brand: 'brp',
    year: 2024,
    price: 1450000,
    rentalPrice: 8000,
    images: ['/images/vehicles/renegade-900.webp'],
    description: 'Универсальный трейловый снегоход Ski-Doo. Комфортная езда по подготовленным трассам и лёгкому бездорожью.',
    specs: {
      engine: 'Rotax 900 ACE Turbo',
      power: '150 л.с.',
      weight: '227 кг',
      maxSpeed: '170 км/ч',
      fuelCapacity: '36 л',
    },
    isAvailable: true,
    isRentable: true,
    isFeatured: false,
  },
  {
    id: '12',
    slug: 'polaris-sportsman-touring-570',
    name: 'Polaris Sportsman Touring 570',
    type: 'atv',
    brand: 'polaris',
    year: 2024,
    price: 1150000,
    rentalPrice: 7000,
    images: ['/images/vehicles/sportsman-touring-570.webp'],
    description: 'Двухместный квадроцикл Polaris для туризма. Комфортное сиденье для пассажира и мощный двигатель.',
    specs: {
      engine: 'ProStar 567 куб.см',
      power: '44 л.с.',
      weight: '317 кг',
      maxSpeed: '95 км/ч',
      fuelCapacity: '17.1 л',
    },
    isAvailable: true,
    isRentable: true,
    isFeatured: false,
  },
];

export function getVehicleBySlug(slug: string): Vehicle | undefined {
  return vehicles.find(v => v.slug === slug);
}

export function getVehiclesByType(type: string): Vehicle[] {
  return vehicles.filter(v => v.type === type);
}

export function getVehiclesByBrand(brand: string): Vehicle[] {
  return vehicles.filter(v => v.brand === brand);
}

export function getFeaturedVehicles(): Vehicle[] {
  return vehicles.filter(v => v.isFeatured);
}

export function getRentableVehicles(): Vehicle[] {
  return vehicles.filter(v => v.isRentable);
}
